namespace SpriteKind {
    export const badguy = SpriteKind.create()
}
controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    Render.jump(mySprite, 100)
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    projectile = sprites.createProjectileFromSprite(img`
        . 4 4 . 
        4 5 5 4 
        2 5 5 2 
        . 2 2 . 
        `, mySprite, 100 * Render.getAttribute(Render.attribute.dirX), 100 * Render.getAttribute(Render.attribute.dirY))
    projectile.setFlag(SpriteFlag.AutoDestroy, false)
    projectile.setKind(SpriteKind.Food)
})
sprites.onOverlap(SpriteKind.badguy, SpriteKind.Food, function (sprite, otherSprite) {
    statusbar.value += 1
    pause(200)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    playerhealth.value += 1
    pause(200)
})
let projectile2: Sprite = null
let projectile: Sprite = null
let playerhealth: StatusBarSprite = null
let statusbar: StatusBarSprite = null
let mySprite: Sprite = null
mySprite = Render.getRenderSpriteVariable()
tiles.setCurrentTilemap(tilemap`level1`)
Render.moveWithController(2)
let mySprite2 = sprites.create(img`
    . . . . . . f f f f . . . . . . 
    . . . . f f 1 1 1 1 f f . . . . 
    . . . f b 1 1 1 1 1 1 b f . . . 
    . . . f 1 1 1 1 1 1 1 1 f . . . 
    . . f d 1 1 1 1 1 1 1 1 d f . . 
    . . f d 1 1 1 1 1 1 1 1 d f . . 
    . . f d d d 1 1 1 1 d d d f . . 
    . . f b d b f d d f b d b f . . 
    . . f c d c f 1 1 f c d c f . . 
    . . . f b 1 1 1 1 1 1 b f . . . 
    . . f f f c d b 1 b d f f f f . 
    f c 1 1 1 c b f b f c 1 1 1 c f 
    f 1 b 1 b 1 f f f f 1 b 1 b 1 f 
    f b f b f f f f f f b f b f b f 
    . . . . . f f f f f f . . . . . 
    . . . . . . . f f f . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.badguy)
mySprite2.setVelocity(50, 50)
mySprite2.setBounceOnWall(true)
tiles.placeOnRandomTile(mySprite, assets.tile`transparency16`)
statusbar = statusbars.create(100, 10, StatusBarKind.Health)
statusbar.setColor(2, 8)
statusbar.value = 0
statusbar.positionDirection(CollisionDirection.Top)
statusbar.setStatusBarFlag(StatusBarFlag.SmoothTransition, true)
playerhealth = statusbars.create(50, 10, StatusBarKind.Health)
playerhealth.setColor(2, 5)
playerhealth.value = 0
playerhealth.positionDirection(CollisionDirection.Bottom)
playerhealth.setStatusBarFlag(StatusBarFlag.SmoothTransition, true)
forever(function () {
    animation.runImageAnimation(
    mySprite2,
    [img`
        ........................
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .....fffc1111111f.......
        ...fc111cd1111111f......
        ...f1b1b1b1111dddf......
        ...fbfbffcf11fcddf......
        ......fcf111111bbf......
        .......ccbdb1b1fcf......
        .......fffbfbfdff.......
        ........ffffffff........
        ........fffffffffff.....
        .........fffffc111cf....
        .........fffff1b1b1f....
        ..........ffffbfbfbf....
        ...........ffff.........
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ....7.fd11111111df......
        ...7..fd11111111df......
        ...7..fd11111111df......
        ...7..fddd1111dddff.....
        ...77.fbdbfddfbdbfcf....
        ...777fcdcf11fcdcfbf....
        ....77fffbdb1bdffcf.....
        ....fcb1bcffffff........
        ....f1c1c1ffffff........
        ....fdfdfdfffff.........
        .....f.f.f..............
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd111111111f......
        ......fd11111111df......
        ......fd11111111df......
        ......fcdd1111ddcff.....
        .......fbcf11fcbfbbf....
        .......ffbdb1bdffff.....
        ........fcbfbfdf........
        ........ffffffff........
        ......ffffffffff........
        .....fcb1bcffff.........
        ......ffbff.............
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fdd111111ddf......
        ......fbdd1111dddf......
        ......fcdbfddfbdbf......
        .......fbcf11fcbfff.....
        .......ffb1111bcfbcf....
        ........fcdb1bdfbbbf....
        .......ffffffffffcf.....
        .....fcb1bcfffff........
        .....f1b1b1ffff.........
        ......ffbff.............
        ........................
        ........................
        ........................
        ........................
        ........................
        `],
    100,
    false
    )
    projectile2 = sprites.createProjectileFromSprite(img`
        . . . . 1 1 1 1 1 1 1 . . . . 
        . . 1 1 1 1 1 1 1 1 1 1 1 . . 
        . 1 1 1 1 1 1 1 1 1 1 1 1 1 . 
        . 1 1 1 f f 1 1 1 f f 1 1 1 . 
        1 1 1 1 f f 1 1 1 f f 1 1 1 1 
        1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 
        1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 
        1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 
        1 1 1 1 1 1 f f f 1 1 1 1 1 1 
        1 1 1 1 1 1 f 1 f 1 1 1 1 1 1 
        1 1 1 1 1 1 f f f 1 1 1 1 1 1 
        . 1 1 1 1 1 1 1 1 1 1 1 1 1 . 
        . 1 1 1 1 1 1 1 1 1 1 1 1 1 . 
        . . 1 1 1 1 1 1 1 1 1 1 1 . . 
        . . . . 1 1 1 1 1 1 1 . . . . 
        `, mySprite2, mySprite.x - mySprite2.x, mySprite.y - mySprite2.y)
    projectile2.setKind(SpriteKind.Enemy)
    projectile2.setFlag(SpriteFlag.AutoDestroy, false)
    pause(1500)
})
